---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Nextcloud:
        icon: nextcloud.png
        href: https://cloud.tribbleshare.de/
        description: Remote-Zusammenarbeit leicht gemacht
    - NASsaja:
        icon: ugreen.png
        href: http://nassaja.follow-inconnu.ts.net:9999/
        description: Huge Capacity | Easy to Use | Secure
    - paperless:
        icon: paperless.png
        href: http://nassaja.follow-inconnu.ts.net:8777/
        description: scan, index and archive all your documents
        widget:
          type: paperlessngx
          url: http://nassaja.follow-inconnu.ts.net:8777/
          key: ***********************
- Wetter:
    - Weimar:
        icon: https://noadsweather.com/favicon.ico
        href:  https://noadsweather.com/?q=Weimar&lat=50.9827&lon=10.9613&name=Weimar&region=Th%C3%BCringen&country=Germany
        description: NoAdsWeather Weimar
    - Mühlwärts:
        icon: https://noadsweather.com/favicon.ico
        href:  https://noadsweather.com/?q=M%C3%BChlw%C3%A4rts&lat=50.7847&lon=9.9814&name=M%C3%BChlw%C3%A4rts&region=Th%C3%BCringen&country=Germany
        description: NoAdsWeather Mühlwärts
