---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: tribbleshare.de
description: Homepage for KaT and Owlbear 
background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
iconStyle: theme # optional, defaults to gradient
showStats: true
language: de
headerStyle: boxed
statusStyle: basic

providers:
  # openweathermap: openweathermapapikey
  # weatherapi: weatherapiapikey

