---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: tribbleshare.de
description: Homepage for KaT and Owlbear
background:
  #image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  image: /images/1920-1080-max.png
  blur: md # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 70 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 30 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
iconStyle: theme # optional, defaults to gradient
showStats: true
language: en
headerStyle: boxed
statusStyle: basic

layout:
  Media:
    style: row
    columns: 3

providers:
# openweathermap: openweathermapapikey
# weatherapi: weatherapiapikey

