services:
 # app:
 #   image: 'docker.io/jc21/nginx-proxy-manager:latest'
 #   container_name: nginx-proxy-manager
 #   restart: unless-stopped
 #   ports:
      #- '80:80'
 #     - '81:81'
 #     - '443:443'
 #   volumes:
 #     - ./proxy_data:/data
 #     - ./proxy_letsencrypt:/etc/letsencrypt


  emby:
    image: emby/embyserver
    restart: unless-stopped
    container_name: emby
    #runtime: nvidia # Expose NVIDIA GPUs
    #network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=1000 # The GID to run emby as (default 2)
      - GIDLIST=1000 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ./emby_data/config:/config # Configuration directory
      - ./emby_data/demo:/mnt/demo # Media directory
      - ./emby_data/shows:/mnt/shows # Media directory
      - ./emby_data/movies:/mnt/movies # Media directory
      - ./emby_data/music:/mnt/music # Media directory
    ports:
      - "8096:8096" # HTTP port
      # - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    labels:
      - homepage.group=Media
      - homepage.name=Emby
      - homepage.icon=emby.png
      - homepage.href=http://tribbleshare.follow-inconnu.ts.net:8096/
      - homepage.description=Filme + Serien
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest #
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - ./mealie_data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Berlin"
      BASE_URL: http://tribbleshare.follow-inconnu.ts.net:9925/
    labels:
      - homepage.group=Essen
      - homepage.name=Mealie
      - homepage.icon=https://docs.mealie.io/assets/img/favicon.png
      - homepage.href=http://tribbleshare.follow-inconnu.ts.net:9925/
      - homepage.description=Rezept Manager

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
    volumes:
      - ./homepage_config:/app/config # Make sure your local config directory exists
    environment:
      HOMEPAGE_ALLOWED_HOSTS: tribbleshare.follow-inconnu.ts.net
      PUID: 1000
      PGID: 1000
    labels:
      - homepage.group=Server Tools
      - homepage.name=Homepage
      - homepage.icon=homepage.png
      - homepage.href=http://tribbleshare.follow-inconnu.ts.net/
      - homepage.description=Aktuelle Seite
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped